### ISSUE TITLE
unsubscribe method

### ISSUE THREAD

**Issue by g-apparence** [glassfy/glassfy-flutter#11]
Hi, 
Im' currently testing this well documented plugin. 
But there is something that I can't find anywhere. 

How can we cancel a user subscription? 
I can't find any method or documentation for this.

**Comment by g-apparence** [comment]
Also could you tell me about "restorePurchases"
It is the closest method of a subscription cancel I've found. 

If we have a user that cancel a subscription after one year of use.
- Does it restore all previous months? 
I'm sorry but I can't really understand and I'm maybe not the only one.

**Comment by g-apparence** [comment]
ok, I will answer for those who like me got used to do this from their Android device. 
Simply prefer use the launch_url plugin to redirect user to playstore or app store subscription management page. 

Maybe this could be great and really easy to provide this directly into the plugin. 
The glassfy plugin is great!
Some comments and doc in code could help and attract many more developpers.

**Comment by marcopifferi** [comment]
It is is not possible to programmatically cancel the subscription: the user needs to go to the play or App Store to cancel the subscription
