### ISSUE TITLE
Gray screen when downloaded from appstore. Not testable locally

### ISSUE THREAD

**Issue by TheRedSpy15** [glassfy/glassfy-flutter#12]
I released an app to both stores. It works perfectly on the playstore. And it works perfectly when running with 'flutter run' and 'flutter run --release' on a physical iOS device.

However, if I download the iOS version from the appstore. My paywall screen that loads the pricing information for my subscription is completely gray. It's almost like there is an error message there but not displaying because it's the production build

Again, there does not appear when downloaded / running the app from any other means that I've tested

**Comment by marcopifferi** [comment]
Could you please send a screenshot ? We are not able to reproduce the issue

**Comment by TheRedSpy15** [comment]
The solution was to not obfuscate the IPA when building. Not sure why exactly, but a simple `flutter build ipa` was required to fix the issue when publishing to the App Store
