### ISSUE TITLE
Support for macos and web

### ISSUE THREAD

**Issue by johnareid54** [glassfy/glassfy-flutter#2]
I have just started using galssfy and the documentation is first class and a lot easier to setup than some other well known purchase package.
Currently the package only supports IOS and android. Is there any plans to include macos and web built using flutter?

**Comment by lgarbo** [comment]
Hi, thanks for the feedback! In next release we'll add support to macOS and we will look for Web support in a future version. If you have other question, please join our [Slack channel](https://bit.ly/3yZEcwj).
