### ISSUE TITLE
Support for paywall remote

### ISSUE THREAD

**Issue by kellvembarbosa** [glassfy/glassfy-flutter#3]
I would like to request the possibility of remote paywall in Flutter,

I know that flutter may not be the main objective of the company since I contacted you in the past about the subject.

I was well attended but now several months later, it is still not possible to call the remote paywall via flutter.

Today it is a gap in flutter the only company that gives real support to flutter with remote paywall and works in a limited way is NamiML where the paid plans are $199, thus limiting the possibility of use.

Pay attention, Flutter grows more and more every day and is a market with weak package competition.

**Comment by lgarbo** [comment]
Thanks for your feedback. 
Paywall support is planned in the roadmap and we will notify you here once that’s released. 
Don’t hesitate to check in with us on chat or at support@glassfy.io
